package cashcow

case class Currency(code: String, name: String)

object Currency {

  object AED extends Currency("AED", "UAE Dirham")
  object AFN extends Currency("AFN", "Afghani")
  object ALL extends Currency("ALL", "Lek")
  object AMD extends Currency("AMD", "Armenian Dram")
  object ANG extends Currency("ANG", "Netherlands Antillean Guilder")
  object AOA extends Currency("AOA", "Kwanza")
  object ARS extends Currency("ARS", "Argentine Peso")
  object AUD extends Currency("AUD", "Australian Dollar")
  object AWG extends Currency("AWG", "Aruban Florin")
  object AZN extends Currency("AZN", "Azerbaijanian Manat")
  object BAM extends Currency("BAM", "Convertible Mark")
  object BBD extends Currency("BBD", "Barbados Dollar")
  object BDT extends Currency("BDT", "Taka")
  object BGN extends Currency("BGN", "Bulgarian Lev")
  object BHD extends Currency("BHD", "Bahraini Dinar")
  object BIF extends Currency("BIF", "Burundi Franc")
  object BMD extends Currency("BMD", "Bermudian Dollar")
  object BND extends Currency("BND", "Brunei Dollar")
  object BOB extends Currency("BOB", "Boliviano")
  object BOV extends Currency("BOV", "Mvdol")
  object BRL extends Currency("BRL", "Brazilian Real")
  object BSD extends Currency("BSD", "Bahamian Dollar")
  object BTN extends Currency("BTN", "Ngultrum")
  object BWP extends Currency("BWP", "Pula")
  object BYN extends Currency("BYN", "Belarusian Ruble")
  object BYR extends Currency("BYR", "Belarusian Ruble")
  object BZD extends Currency("BZD", "Belize Dollar")
  object CAD extends Currency("CAD", "Canadian Dollar")
  object CDF extends Currency("CDF", "Congolese Franc")
  object CHE extends Currency("CHE", "WIR Euro")
  object CHF extends Currency("CHF", "Swiss Franc")
  object CHW extends Currency("CHW", "WIR Franc")
  object CLF extends Currency("CLF", "Unidad de Fomento")
  object CLP extends Currency("CLP", "Chilean Peso")
  object CNY extends Currency("CNY", "Yuan Renminbi")
  object COP extends Currency("COP", "Colombian Peso")
  object COU extends Currency("COU", "Unidad de Valor Real")
  object CRC extends Currency("CRC", "Costa Rican Colon")
  object CUC extends Currency("CUC", "Peso Convertible")
  object CUP extends Currency("CUP", "Cuban Peso")
  object CVE extends Currency("CVE", "Cabo Verde Escudo")
  object CZK extends Currency("CZK", "Czech Koruna")
  object DJF extends Currency("DJF", "Djibouti Franc")
  object DKK extends Currency("DKK", "Danish Krone")
  object DOP extends Currency("DOP", "Dominican Peso")
  object DZD extends Currency("DZD", "Algerian Dinar")
  object EGP extends Currency("EGP", "Egyptian Pound")
  object ERN extends Currency("ERN", "Nakfa")
  object ETB extends Currency("ETB", "Ethiopian Birr")
  object EUR extends Currency("EUR", "Euro")
  object FJD extends Currency("FJD", "Fiji Dollar")
  object FKP extends Currency("FKP", "Falkland Islands Pound")
  object GBP extends Currency("GBP", "Pound Sterling")
  object GEL extends Currency("GEL", "Lari")
  object GHS extends Currency("GHS", "Ghana Cedi")
  object GIP extends Currency("GIP", "Gibraltar Pound")
  object GMD extends Currency("GMD", "Dalasi")
  object GNF extends Currency("GNF", "Guinea Franc")
  object GTQ extends Currency("GTQ", "Quetzal")
  object GYD extends Currency("GYD", "Guyana Dollar")
  object HKD extends Currency("HKD", "Hong Kong Dollar")
  object HNL extends Currency("HNL", "Lempira")
  object HRK extends Currency("HRK", "Kuna")
  object HTG extends Currency("HTG", "Gourde")
  object HUF extends Currency("HUF", "Forint")
  object IDR extends Currency("IDR", "Rupiah")
  object ILS extends Currency("ILS", "New Israeli Sheqel")
  object INR extends Currency("INR", "Indian Rupee")
  object IQD extends Currency("IQD", "Iraqi Dinar")
  object IRR extends Currency("IRR", "Iranian Rial")
  object ISK extends Currency("ISK", "Iceland Krona")
  object JMD extends Currency("JMD", "Jamaican Dollar")
  object JOD extends Currency("JOD", "Jordanian Dinar")
  object JPY extends Currency("JPY", "Yen")
  object KES extends Currency("KES", "Kenyan Shilling")
  object KGS extends Currency("KGS", "Som")
  object KHR extends Currency("KHR", "Riel")
  object KMF extends Currency("KMF", "Comoro Franc")
  object KPW extends Currency("KPW", "North Korean Won")
  object KRW extends Currency("KRW", "Won")
  object KWD extends Currency("KWD", "Kuwaiti Dinar")
  object KYD extends Currency("KYD", "Cayman Islands Dollar")
  object KZT extends Currency("KZT", "Tenge")
  object LAK extends Currency("LAK", "Kip")
  object LBP extends Currency("LBP", "Lebanese Pound")
  object LKR extends Currency("LKR", "Sri Lanka Rupee")
  object LRD extends Currency("LRD", "Liberian Dollar")
  object LSL extends Currency("LSL", "Loti")
  object LYD extends Currency("LYD", "Libyan Dinar")
  object MAD extends Currency("MAD", "Moroccan Dirham")
  object MDL extends Currency("MDL", "Moldovan Leu")
  object MGA extends Currency("MGA", "Malagasy Ariary")
  object MKD extends Currency("MKD", "Denar")
  object MMK extends Currency("MMK", "Kyat")
  object MNT extends Currency("MNT", "Tugrik")
  object MOP extends Currency("MOP", "Pataca")
  object MRO extends Currency("MRO", "Ouguiya")
  object MUR extends Currency("MUR", "Mauritius Rupee")
  object MVR extends Currency("MVR", "Rufiyaa")
  object MWK extends Currency("MWK", "Malawi Kwacha")
  object MXN extends Currency("MXN", "Mexican Peso")
  object MXV extends Currency("MXV", "Mexican Unidad de Inversion (UDI)")
  object MYR extends Currency("MYR", "Malaysian Ringgit")
  object MZN extends Currency("MZN", "Mozambique Metical")
  object NAD extends Currency("NAD", "Namibia Dollar")
  object NGN extends Currency("NGN", "Naira")
  object NIO extends Currency("NIO", "Cordoba Oro")
  object NOK extends Currency("NOK", "Norwegian Krone")
  object NPR extends Currency("NPR", "Nepalese Rupee")
  object NZD extends Currency("NZD", "New Zealand Dollar")
  object OMR extends Currency("OMR", "Rial Omani")
  object PAB extends Currency("PAB", "Balboa")
  object PEN extends Currency("PEN", "Sol")
  object PGK extends Currency("PGK", "Kina")
  object PHP extends Currency("PHP", "Philippine Peso")
  object PKR extends Currency("PKR", "Pakistan Rupee")
  object PLN extends Currency("PLN", "Zloty")
  object PYG extends Currency("PYG", "Guarani")
  object QAR extends Currency("QAR", "Qatari Rial")
  object RON extends Currency("RON", "Romanian Leu")
  object RSD extends Currency("RSD", "Serbian Dinar")
  object RUB extends Currency("RUB", "Russian Ruble")
  object RWF extends Currency("RWF", "Rwanda Franc")
  object SAR extends Currency("SAR", "Saudi Riyal")
  object SBD extends Currency("SBD", "Solomon Islands Dollar")
  object SCR extends Currency("SCR", "Seychelles Rupee")
  object SDG extends Currency("SDG", "Sudanese Pound")
  object SEK extends Currency("SEK", "Swedish Krona")
  object SGD extends Currency("SGD", "Singapore Dollar")
  object SHP extends Currency("SHP", "Saint Helena Pound")
  object SLL extends Currency("SLL", "Leone")
  object SOS extends Currency("SOS", "Somali Shilling")
  object SRD extends Currency("SRD", "Surinam Dollar")
  object SSP extends Currency("SSP", "South Sudanese Pound")
  object STD extends Currency("STD", "Dobra")
  object SVC extends Currency("SVC", "El Salvador Colon")
  object SYP extends Currency("SYP", "Syrian Pound")
  object SZL extends Currency("SZL", "Lilangeni")
  object THB extends Currency("THB", "Baht")
  object TJS extends Currency("TJS", "Somoni")
  object TMT extends Currency("TMT", "Turkmenistan New Manat")
  object TND extends Currency("TND", "Tunisian Dinar")
  object TOP extends Currency("TOP", "Pa’anga")
  object TRY extends Currency("TRY", "Turkish Lira")
  object TTD extends Currency("TTD", "Trinidad and Tobago Dollar")
  object TWD extends Currency("TWD", "New Taiwan Dollar")
  object TZS extends Currency("TZS", "Tanzanian Shilling")
  object UAH extends Currency("UAH", "Hryvnia")
  object UGX extends Currency("UGX", "Uganda Shilling")
  object USD extends Currency("USD", "US Dollar")
  object USN extends Currency("USN", "US Dollar (Next day)")
  object UYI extends Currency("UYI", "Uruguay Peso en Unidades Indexadas (URUIURUI)")
  object UYU extends Currency("UYU", "Peso Uruguayo")
  object UZS extends Currency("UZS", "Uzbekistan Sum")
  object VEF extends Currency("VEF", "Bolívar")
  object VND extends Currency("VND", "Dong")
  object VUV extends Currency("VUV", "Vatu")
  object WST extends Currency("WST", "Tala")
  object XAF extends Currency("XAF", "CFA Franc BEAC")
  object XAG extends Currency("XAG", "Silver")
  object XAU extends Currency("XAU", "Gold")
  object XBA extends Currency("XBA", "Bond Markets Unit European Composite Unit (EURCO)")
  object XBB extends Currency("XBB", "Bond Markets Unit European Monetary Unit (E.M.U.-6)")
  object XBC extends Currency("XBC", "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)")
  object XBD extends Currency("XBD", "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)")
  object XCD extends Currency("XCD", "East Caribbean Dollar")
  object XDR extends Currency("XDR", "SDR (Special Drawing Right)")
  object XOF extends Currency("XOF", "CFA Franc BCEAO")
  object XPD extends Currency("XPD", "Palladium")
  object XPF extends Currency("XPF", "CFP Franc")
  object XPT extends Currency("XPT", "Platinum")
  object XSU extends Currency("XSU", "Sucre")
  object XTS extends Currency("XTS", "Codes specifically reserved for testing purposes")
  object XUA extends Currency("XUA", "ADB Unit of Account")
  object XXX extends Currency("XXX", "The codes assigned for transactions where no currency is involved")
  object YER extends Currency("YER", "Yemeni Rial")
  object ZAR extends Currency("ZAR", "Rand")
  object ZMW extends Currency("ZMW", "Zambian Kwacha")
  object ZWL extends Currency("ZWL", "Zimbabwe Dollar")

}

object Test extends App {

  import Currency._

  val eur_usd = EUR / JPY
  val eur_usd2: CurrencyPair = EUR / Currency("FF", "Fucks")
  println(eur_usd)

}


